name: symptom-tracking
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - catboost
  - plotly
  - tqdm
  - pyyaml
  - gitpython
  - typing-extensions
  - openjdk=17
  - ca-certificates
  - joblib
  - shap
  - pip
  - pip:
      - configargparse==1.7
      - dill==0.3.8
      - tensorboard==2.16.2
